### ISSUE TITLE
Código no portable

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-boom-1#2]
En vuestro código empleáis llamadas a comandos específicos de Windows. Esto hace que vuestro código no sea portable, es decir, no se puede compilar o ejecutar en otros sistemas operativos.
Por ejemplo, system(cls): https://www.daniweb.com/programming/software-development/threads/95284/clearing-screen-in-the-console
En particular, las pruebas de código tras la entrega final se harán con sistema automático que trabaja en Linux, debéis evitar estas llamadas.

**Comment by oscararrigo** [comment]
Problema solucionado, gracias
